"""Подсветка синтаксиса и определение лексеров для вывода."""


_EXT_LEXER_MAP = {
    "py": "python",
    "js": "javascript",
    "ts": "typescript",
    "json": "json",
    "yaml": "yaml",
    "yml": "yaml",
    "toml": "toml",
    "xml": "xml",
    "html": "html",
    "css": "css",
    "sh": "bash",
    "bash": "bash",
    "rs": "rust",
    "go": "go",
    "rb": "ruby",
    "cpp": "cpp",
    "c": "c",
    "h": "c",
    "hpp": "cpp",
    "java": "java",
    "kt": "kotlin",
    "sql": "sql",
    "md": "markdown",
    "conf": "ini",
    "cfg": "ini",
    "ini": "ini",
    "env": "bash",
    "dockerfile": "docker",
    "tsx": "typescript",
    "jsx": "javascript",
    "vue": "vue",
    "svelte": "html",
    "scss": "scss",
    "less": "less",
    "lua": "lua",
    "php": "php",
    "swift": "swift",
    "r": "r",
    "pl": "perl",
    "tf": "terraform",
    "hcl": "terraform",
    "zig": "zig",
    "nim": "nim",
    "dart": "dart",
}
